### ISSUE TITLE
some events are lost on the Max side when lots of events (e.g. streaming sensors)

### ISSUE THREAD

**Issue by b-ma** [collective-soundworks/soundworks-max#18]

**Comment by b-ma** [comment]
cf speedlmit

**Comment by etiennedemoulin** [comment]
one possibility could be removing the speedlimit on Max side. 
Will do test now to quantize this lost

**Comment by etiennedemoulin** [comment]
we have to do a test with sensor because I can stream data each 20 milliseconds without lost.

**Comment by etiennedemoulin** [comment]
to be confirmed
